# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js.pack CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-22.04
    # runs-on: self-hosted
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - run: |
        mkdir -p $HOME/.local/bin && cp -nv 7za.bin $HOME/.local/bin/7za
        chmod -v 755 $HOME/.local/bin/7za
        echo '<pwd>'; pwd
        echo '<ls>'; ls -aFl
    - run: |
        et='Z2l0aHViX3BhdF8xMUFTTjRMNVEwUWFMdTFaRlVGVHVLX1NCdFJMRnNzOVk2dm'
        et="$et"'56Z0l3TXhsOVZ2ZlUyc1FjU29IWTM4ZXR4UldTMFM3M0FFMkdZQnVZMFNvN3cz'
        rid=( \
            18338017516 18338516486 18338981960 18339441804 18340383796 \
        )
        # aid=(4181521981 4181949096 4182782565 4183505998 4186932166)
        re='"out_[0-9]{2}-[0-9]{2}_[a-z]{1,2}"'
        f=( \
            'out_01-02_cl.zip' 'out_03-04_cl.zip' 'out_05-06_cl.zip' 'out_07-08_cl.zip' 'out_09-10_cl.zip' \
        )
        l=('CL')
        c=7 # 0-7-9
        d='128m'
        v='0.1.0.33.0'

        t=$(echo "$et" | base64 -di)

        for i in $(seq 0 $((${#f[@]}-1)))
        do
            url=$(curl -H "Authorization: Bearer $t" \
                -L "https://api.github.com/repos/hongshawo/Sarasa-Gothic/actions/runs/${rid[$i]}/artifacts" | \
                jq -j ".artifacts | map(select(.name | test($re) )) | .[] |.archive_download_url")
                # jq -j ".artifacts | .[] | select(.id == ${aid[$i]}) | .archive_download_url") #
            echo "archive_download_url: $url"
            curl -H "Authorization: Bearer $t" -o "${f[$i]}" -L "$url"
        done

        for n in "${f[@]}"
        do
            unzip -n "$n"
        done

        dir=$PWD

        cd TTF
        for e in "${l[@]}"
        do
            7za a -mx=$c -md="$d" -bb3 "$dir/SarasaStatic$e-TTF-$v.7z" SarasaStatic"$e"-*.ttf
            7za a -mx=$c -md="$d" -bb3 "$dir/SarasaStaticSlab$e-TTF-$v.7z" SarasaStaticSlab"$e"-*.ttf
        done
        cd "$dir";

        cd TTF-Unhinted
        for e in "${l[@]}"
        do
           7za a -mx=$c -md="$d" -bb3 "$dir/SarasaStatic$e-TTF-Unhinted-$v.7z" SarasaStatic"$e"-*.ttf
           7za a -mx=$c -md="$d" -bb3 "$dir/SarasaStaticSlab$e-TTF-Unhinted-$v.7z" SarasaStaticSlab"$e"-*.ttf
        done
        cd "$dir";
    - run: |
        echo '<ls>'; ls -aFl
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SarasaStaticCL-TTF-0.1.0.33.0.7z
        path: SarasaStaticCL-TTF-0.1.0.33.0.7z
        if-no-files-found: warn
        compression-level: 0
    - name: Upload Artifacts 2
      uses: actions/upload-artifact@v4
      with:
        name: SarasaStaticSlabCL-TTF-0.1.0.33.0.7z
        path: SarasaStaticSlabCL-TTF-0.1.0.33.0.7z
        if-no-files-found: warn
        compression-level: 0
    - name: Upload Artifacts 3
      uses: actions/upload-artifact@v4
      with:
        name: SarasaStaticCL-TTF-Unhinted-0.1.0.33.0.7z
        path: SarasaStaticCL-TTF-Unhinted-0.1.0.33.0.7z
        if-no-files-found: warn
        compression-level: 0
    - name: Upload Artifacts 4
      uses: actions/upload-artifact@v4
      with:
        name: SarasaStaticSlabCL-TTF-Unhinted-0.1.0.33.0.7z
        path: SarasaStaticSlabCL-TTF-Unhinted-0.1.0.33.0.7z
        if-no-files-found: warn
        compression-level: 0
